# Generated by Django 3.2.5 on 2023-03-25 05:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('mac_address', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cluster',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(default='Not running', max_length=100)),
                ('clusterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cluster', to='manager.cluster')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='EmotionLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('neutral', models.IntegerField(default=0)),
                ('happiness', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
                ('sadness', models.IntegerField(default=0)),
                ('anger', models.IntegerField(default=0)),
                ('disgust', models.IntegerField(default=0)),
                ('fear', models.IntegerField(default=0)),
                ('contempt', models.IntegerField(default=0)),
                ('lessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_lesson', to='manager.lesson')),
            ],
            options={
                'db_table': 'emotion_lesson',
            },
        ),
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_url', models.CharField(max_length=250)),
                ('clusterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_cluster', to='manager.cluster')),
            ],
            options={
                'db_table': 'configure',
            },
        ),
        migrations.CreateModel(
            name='CaptureImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('clusterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_cluster_capture', to='manager.cluster')),
            ],
            options={
                'db_table': 'capture_image',
            },
        ),
    ]
