# Generated by Django 3.2.5 on 2023-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlesson',
            name='fps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_anger',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_contempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_disgust',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_fear',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_happiness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_sadness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='latest_surprise',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='lesson_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='normal_student',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotionlesson',
            name='student',
            field=models.IntegerField(default=0),
        ),
    ]
